---
- hosts: all
  become: yes

  vars:
    - homeDir: /home/ubuntu
    - appDir : app

  tasks:
    - name: install nodejs prerequisites
      apt:
        name:
          - apt-transport-https
          - python3
        state: latest
        update_cache: yes
        
    - name: add nodejs apt key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
        
    - name: add nodejs repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x {{ ansible_lsb.codename }} main
        state: present
        update_cache: yes
        
    - name: install nodejs
      apt:
        name: nodejs
        state: latest

    - name: Install pm2
      npm: name=pm2 global=yes production=yes

    - name: Create APP Directory
      file: path={{homeDir}}/{{appDir}} state=directory

    - name: Git checkout website
      git:
        repo: https://Ombrelin:{{github_token}}@github.com/Incident-Ticket-Manager/backend.git
        dest: path={{homeDir}}/{{appDir}}
      register: git_finished
    
    - name: Running NPM install
      npm: path={{homeDir}}/{{appDir}}/backend
      register: npm_finished
      when: git_finished.changed

    - name: Start APP
      command: pm2 start {{homeDir}}/{{appDir}}/backend/bin/www --name app
      when: npm_finished.changed
      environment:
        - SECRET=MA5y3KZGmjSS5dp@
        - PORT=3000
        - DATABASE_URL={{database_url}}
